import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppSidebar } from "@/components/ui/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider"

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
          <html lang="en" suppressHydrationWarning>

      <body>
        <SidebarProvider>
          <AppSidebar />
          <main className="flex-1 w-full">
            <SidebarTrigger />
            <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            </ThemeProvider>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
